# Your configuration properties
quarkus.rest-client.repositorio-client.url=http://localhost:8085
quarkus.rest-client.repositorio-token.url=http://localhost:8085/repositorio
quarkus.rest-client.repositorio-client.verify-host=false

quarkus.datasource.db-kind=h2
quarkus.datasource.username=username-default
quarkus.datasource.jdbc.url=jdbc:h2:mem:default
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.sql-load-script=init.sql

quarkus.http.auth.form.enabled=true
quarkus.http.auth.permission.permit1.paths=/secured/*
quarkus.http.auth.permission.permit1.policy=authenticated
quarkus.http.auth.form.login-page=/login
quarkus.http.auth.form.error-page=/login
quarkus.http.auth.form.landing-page=/secured/listarPendientes


quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true

quarkus.security.users.embedded.users.homer=admin
quarkus.security.users.embedded.roles.homer=ADMIN,USER

quarkus.security.users.embedded.users.bart=admin
quarkus.security.users.embedded.roles.bart=USER

quarkus.security.users.embedded.users.marge=admin
quarkus.security.users.embedded.roles.marge=USER

quarkus.security.users.embedded.users.lisa=admin
quarkus.security.users.embedded.roles.lisa=USER